openapi: 3.0.1
info:
  title: openITCOCKPIT API
  description: 'This is our sample openITCOCKPIT API description. It´s connected to our public demo system [https://demo.openitcockpit.io](https://demo.openitcockpit.io)<br>You can find out more about openITCOCKPIT at [https://openitcockpit.io](https://openitcockpit.io) or use our community IRC Channel at [irc.freenode.net, #openitcockpit](https://kiwiirc.com/nextclient/irc.freenode.net/#openitcockpit).'
  contact:
    email: development@openitcockpit.io
  license:
    name: MIT Licensed
    url: 'https://raw.githubusercontent.com/it-novum/openITCOCKPIT-API-docs/master/LICENSE'
  version: 4.3.0
externalDocs:
  description: Complete technical documentation
  url: 'https://docs.openitcockpit.io/'
servers:
  - url: 'https://demo.openitcockpit.io'
tags:
  - name: Commands
    description: Basic Monitoring
  - name: Time periods
    description: Basic Monitoring
  - name: Contacts
    description: Basic Monitoring
  - name: Contact groups
    description: Basic Monitoring
  - name: Host templates
    description: Basic Monitoring
  - name: Host groups
    description: Basic Monitoring
  - name: Hosts
    description: Basic Monitoring
  - name: Service templates
    description: Basic Monitoring
  - name: Service groups
    description: Basic Monitoring
  - name: Service template groups
    description: Basic Monitoring
  - name: Services
    description: Basic Monitoring
  - name: Users
    description: User Management
  - name: Agent
    description: Agent
paths:
  /commands/index.json:
    $ref: "./external/commands.yaml#/requests/index"
  /commands/add.json:
    $ref: "./external/commands.yaml#/requests/add"
  /commands/edit/{commandId}.json:
    $ref: "./external/commands.yaml#/requests/edit"
  /commands/delete/{commandId}.json:
    $ref: "./external/commands.yaml#/requests/delete"
  /commands/copy/.json:
    $ref: "./external/commands.yaml#/requests/copy"

  /timeperiods/index.json:
    $ref: "./external/timeperiods.yaml#/requests/index"
  /timeperiods/add.json:
    $ref: "./external/timeperiods.yaml#/requests/add"
  /timeperiods/edit/{timeperiodId}.json:
    $ref: "./external/timeperiods.yaml#/requests/edit"
  /timeperiods/delete/{timeperiodId}.json:
    $ref: "./external/timeperiods.yaml#/requests/delete"
  /timeperiods/copy/.json:
    $ref: "./external/timeperiods.yaml#/requests/copy"

  /contacts/index.json:
    $ref: "./external/contacts.yaml#/requests/index"
  /contacts/add.json:
    $ref: "./external/contacts.yaml#/requests/add"
  /contacts/edit/{contactId}.json:
    $ref: "./external/contacts.yaml#/requests/edit"
  /contacts/delete/{contactId}.json:
    $ref: "./external/contacts.yaml#/requests/delete"
  /contacts/copy/.json:
    $ref: "./external/contacts.yaml#/requests/copy"

  /contactgroups/index.json:
    $ref: "./external/contactgroups.yaml#/requests/index"
  /contactgroups/add.json:
    $ref: "./external/contactgroups.yaml#/requests/add"
  /contactgroups/edit/{contactgroupId}.json:
    $ref: "./external/contactgroups.yaml#/requests/edit"
  /contactgroups/delete/{contactgroupId}.json:
    $ref: "./external/contactgroups.yaml#/requests/delete"
  /contactgroups/copy/.json:
    $ref: "./external/contactgroups.yaml#/requests/copy"

  /hosttemplates/index.json:
    $ref: "./external/hosttemplates.yaml#/requests/index"
  /hosttemplates/add.json:
    $ref: "./external/hosttemplates.yaml#/requests/add"
  /hosttemplates/edit/{hosttemplateId}.json:
    $ref: "./external/hosttemplates.yaml#/requests/edit"
  /hosttemplates/delete/{hosttemplateId}.json:
    $ref: "./external/hosttemplates.yaml#/requests/delete"
  /hosttemplates/copy/.json:
    $ref: "./external/hosttemplates.yaml#/requests/copy"

  /hosts/index.json:
    $ref: "./external/hosts.yaml#/requests/index"
  /hosts/add.json:
    $ref: "./external/hosts.yaml#/requests/add"
  /hosts/edit/{hostId}.json:
    $ref: "./external/hosts.yaml#/requests/edit"
  /hosts/delete/{hostId}.json:
    $ref: "./external/hosts.yaml#/requests/delete"

  /servicetemplates/index.json:
    $ref: "./external/servicetemplates.yaml#/requests/index"
  /servicetemplates/add.json:
    $ref: "./external/servicetemplates.yaml#/requests/add"
  /servicetemplates/edit/{servicetemplateId}.json:
    $ref: "./external/servicetemplates.yaml#/requests/edit"
  /servicetemplates/delete/{servicetemplateId}.json:
    $ref: "./external/servicetemplates.yaml#/requests/delete"

  /services/index.json:
    $ref: "./external/services.yaml#/requests/index"
  /services/add.json:
    $ref: "./external/services.yaml#/requests/add"
  /services/edit/{serviceId}.json:
    $ref: "./external/services.yaml#/requests/edit"
  /services/delete/{serviceId}.json:
    $ref: "./external/services.yaml#/requests/delete"

  /users/index.json:
    $ref: "./external/users.yaml#/requests/index"
  /users/add.json:
    $ref: "./external/users.yaml#/requests/add"
  /users/edit/{userId}.json:
    $ref: "./external/users.yaml#/requests/edit"
  /users/delete/{userId}.json:
    $ref: "./external/users.yaml#/requests/delete"

  /hostgroups/index.json:
    $ref: "./external/hostgroups.yaml#/requests/index"
  /hostgroups/add.json:
    $ref: "./external/hostgroups.yaml#/requests/add"
  /hostgroups/edit/{hostgroupId}.json:
    $ref: "./external/hostgroups.yaml#/requests/edit"
  /hostgroups/delete/{hostgroupId}.json:
    $ref: "./external/hostgroups.yaml#/requests/delete"

  /servicegroups/index.json:
    $ref: "./external/servicegroups.yaml#/requests/index"
  /servicegroups/add.json:
    $ref: "./external/servicegroups.yaml#/requests/add"
  /servicegroups/edit/{servicegroupId}.json:
    $ref: "./external/servicegroups.yaml#/requests/edit"
  /servicegroups/delete/{servicegroupId}.json:
    $ref: "./external/servicegroups.yaml#/requests/delete"

  /servicetemplategroups/index.json:
    $ref: "./external/servicetemplategroups.yaml#/requests/index"
  /servicetemplategroups/add.json:
    $ref: "./external/servicetemplategroups.yaml#/requests/add"
  /servicetemplategroups/edit/{servicetemplategroupId}.json:
    $ref: "./external/servicetemplategroups.yaml#/requests/edit"
  /servicetemplategroups/delete/{servicetemplategroupId}.json:
    $ref: "./external/servicetemplategroups.yaml#/requests/delete"

  /agentconnector/config.json:
    $ref: "./external/agent.yaml#/requests/config"
  /agentconnector/install.json:
    $ref: "./external/agent.yaml#/requests/install"
  /agentconnector/autotls.json:
    $ref: "./external/agent.yaml#/requests/autotls"
  /agentconnector/select_agent.json:
    $ref: "./external/agent.yaml#/requests/select_agent"
  /agentconnector/create_services.json:
    $ref: "./external/agent.yaml#/requests/create_services"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apikey
      in: query
