openapi: 3.0.1
info:
  title: openITCOCKPIT API
  description: 'This is a openITCOCKPIT API description (alpha).<br>You can find out more about openITCOCKPIT at [https://openitcockpit.io](https://openitcockpit.io) or use our community IRC Channel at [irc.freenode.net, #openitcockpit](https://kiwiirc.com/nextclient/irc.freenode.net/#openitcockpit).<br><br>For this api sample, you can use the api key `bcc965e7e782d0ce1d86c5c9dfae7aebbd3587e2f90f7e641e795da7f06706e6904d57de3bd600c9b20627737069fc38c4ffd760f777f877f9b7df050029d3ca1df681d807bec276302235fd7193717b` to authorize yourself.'
  contact:
    email: development@openitcockpit.io
  license:
    name: MIT Licensed
    url: 'https://raw.githubusercontent.com/it-novum/openITCOCKPIT-API-docs/master/LICENSE'
  version: 4.0.0
externalDocs:
  description: Complete technical documentation
  url: 'https://docs.it-novum.com/display/ODE'
servers:
  - url: 'https://ttriebensky.oitc.itn'
  - url: 'https://demo.openitcockpit.io'
tags:
  - name: Commands
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462728'
  - name: Time periods
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23463621'
  - name: Contacts
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/display/ODE/Finding+contacts'
  - name: Contact groups
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/display/ODE/Finding+contact+groups'
  - name: Host templates
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462734'
  - name: Host groups
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462730'
  - name: Hosts
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462732'
  - name: Service templates
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462744'
  - name: Service groups
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462736'
  - name: Services
    description: Basic Monitoring
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462740'
  - name: Users
    description: User Management
    externalDocs:
      description: Technical documentation
      url: 'https://docs.it-novum.com/pages/viewpage.action?pageId=23462746'
paths:
  /commands/index.json:
    $ref: "http://localhost:81/commands.yaml#/requests/index"
  /commands/add.json:
    $ref: "http://localhost:81/commands.yaml#/requests/add"
  /commands/edit/{commandId}.json:
    $ref: "http://localhost:81/commands.yaml#/requests/edit"
  /commands/delete/{commandId}.json:
    $ref: "http://localhost:81/commands.yaml#/requests/delete"
  /commands/copy/.json:
    $ref: "http://localhost:81/commands.yaml#/requests/copy"

  /timeperiods/index.json:
    $ref: "http://localhost:81/timeperiods.yaml#/requests/index"
  /timeperiods/add.json:
    $ref: "http://localhost:81/timeperiods.yaml#/requests/add"
  /timeperiods/edit/{timeperiodId}.json:
    $ref: "http://localhost:81/timeperiods.yaml#/requests/edit"
  /timeperiods/delete/{timeperiodId}.json:
    $ref: "http://localhost:81/timeperiods.yaml#/requests/delete"
  /timeperiods/copy/.json:
    $ref: "http://localhost:81/timeperiods.yaml#/requests/copy"

  /contacts/index.json:
    $ref: "http://localhost:81/contacts.yaml#/requests/index"
  /contacts/add.json:
    $ref: "http://localhost:81/contacts.yaml#/requests/add"
  /contacts/edit/{contactId}.json:
    $ref: "http://localhost:81/contacts.yaml#/requests/edit"
  /contacts/delete/{contactId}.json:
    $ref: "http://localhost:81/contacts.yaml#/requests/delete"
  /contacts/copy/.json:
    $ref: "http://localhost:81/contacts.yaml#/requests/copy"

  /contactgroups/index.json:
    $ref: "http://localhost:81/contactgroups.yaml#/requests/index"
  /contactgroups/add.json:
    $ref: "http://localhost:81/contactgroups.yaml#/requests/add"
  /contactgroups/edit/{contactgroupId}.json:
    $ref: "http://localhost:81/contactgroups.yaml#/requests/edit"
  /contactgroups/delete/{contactgroupId}.json:
    $ref: "http://localhost:81/contactgroups.yaml#/requests/delete"
  /contactgroups/copy/.json:
    $ref: "http://localhost:81/contactgroups.yaml#/requests/copy"

  /hosttemplates/index.json:
    $ref: "http://localhost:81/hosttemplates.yaml#/requests/index"
  /hosttemplates/add.json:
    $ref: "http://localhost:81/hosttemplates.yaml#/requests/add"
  /hosttemplates/edit/{hosttemplateId}.json:
    $ref: "http://localhost:81/hosttemplates.yaml#/requests/edit"
  /hosttemplates/delete/{hosttemplateId}.json:
    $ref: "http://localhost:81/hosttemplates.yaml#/requests/delete"
  /hosttemplates/copy/.json:
    $ref: "http://localhost:81/hosttemplates.yaml#/requests/copy"

  /hosts/index.json:
    $ref: "http://localhost:81/hosts.yaml#/requests/index"
  /hosts/add.json:
    $ref: "http://localhost:81/hosts.yaml#/requests/add"
  /hosts/edit/{hostId}.json:
    $ref: "http://localhost:81/hosts.yaml#/requests/edit"
  /hosts/delete/{hostId}.json:
    $ref: "http://localhost:81/hosts.yaml#/requests/delete"

  /servicetemplates/index.json:
    $ref: "http://localhost:81/servicetemplates.yaml#/requests/index"
  /servicetemplates/add.json:
    $ref: "http://localhost:81/servicetemplates.yaml#/requests/add"
  /servicetemplates/edit/{servicetemplateId}.json:
    $ref: "http://localhost:81/servicetemplates.yaml#/requests/edit"
  /servicetemplates/delete/{servicetemplateId}.json:
    $ref: "http://localhost:81/servicetemplates.yaml#/requests/delete"

  /services/index.json:
    $ref: "http://localhost:81/services.yaml#/requests/index"
  /services/add.json:
    $ref: "http://localhost:81/services.yaml#/requests/add"
  /services/edit/{serviceId}.json:
    $ref: "http://localhost:81/services.yaml#/requests/edit"
  /services/delete/{serviceId}.json:
    $ref: "http://localhost:81/services.yaml#/requests/delete"

  /users/index.json:
    $ref: "http://localhost:81/users.yaml#/requests/index"
  /users/add.json:
    $ref: "http://localhost:81/users.yaml#/requests/add"
  /users/edit/{userId}.json:
    $ref: "http://localhost:81/users.yaml#/requests/edit"
  /users/delete/{userId}.json:
    $ref: "http://localhost:81/users.yaml#/requests/delete"

  /hostgroups/index.json:
    $ref: "http://localhost:81/hostgroups.yaml#/requests/index"
  /hostgroups/add.json:
    $ref: "http://localhost:81/hostgroups.yaml#/requests/add"
  /hostgroups/edit/{hostgroupId}.json:
    $ref: "http://localhost:81/hostgroups.yaml#/requests/edit"
  /hostgroups/delete/{hostgroupId}.json:
    $ref: "http://localhost:81/hostgroups.yaml#/requests/delete"

  /servicegroups/index.json:
    $ref: "http://localhost:81/servicegroups.yaml#/requests/index"
  /servicegroups/add.json:
    $ref: "http://localhost:81/servicegroups.yaml#/requests/add"
  /servicegroups/edit/{servicegroupId}.json:
    $ref: "http://localhost:81/servicegroups.yaml#/requests/edit"
  /servicegroups/delete/{servicegroupId}.json:
    $ref: "http://localhost:81/servicegroups.yaml#/requests/delete"


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apikey
      in: query
