requests:
  index:
    get:
      tags:
        - Hosts
      summary: Find hosts
      parameters:
        - name: angular
          in: query
          description: Use angular=true to get API results instead of a html template
          required: true
          schema:
            type: boolean
          example: true
        - name: direction
          in: query
          description: Use direction to sort the response
          required: false
          schema:
            type: string
            default: desc
            items:
              default: desc
              enum:
                - asc
                - desc
        - name: scroll
          in: query
          description: Use scroll instead of paging
          required: true
          schema:
            type: boolean
          example: true
        - name: page
          in: query
          description: Get page (number) of search results
          required: true
          style: form
          schema:
            default: 1
            minimum: 1
            type: integer
            format: int64
        - name: sort
          in: query
          description: The field according to which is sorted in the specified direction
          schema:
            type: string
            example: ""
          example: Hoststatus.current_state
        - name: filter[Hosts.name]
          in: query
          schema:
            type: string
            example: ""
          description: Filter by host name
        - name: filter[Hosts.address]
          in: query
          schema:
            type: string
            example: ""
          description: Filter by host address
        - name: filter[Hosts.description]
          in: query
          schema:
            type: string
            example: ""
          description: Filter by host description
        - name: filter[Hosts.keywords][]
          in: query
          schema:
            type: array
            uniqueItems: true
            items:
              type: string
              additionalProperties: true
          description: Filter by host keywords
        - name: filter[Hosts.not_keywords][]
          in: query
          schema:
            type: array
            uniqueItems: true
            items:
              type: string
              additionalProperties: true
          description: Filter by host has not keywords
        - name: filter[Hosts.satellite_id][]
          in: query
          schema:
            type: array
            uniqueItems: true
            items:
              type: integer
              additionalProperties: true
          description: Filter by satellite id
        - name: filter[Hoststatus.current_state][]
          in: query
          schema:
            type: array
            uniqueItems: true
            items:
              type: string
              enum:
                - up
                - down
                - unreachable
          description: Filter by host keywords
        - name: filter[Hoststatus.output]
          in: query
          schema:
            type: string
          description: Filter by host status output
        - name: filter[Hoststatus.problem_has_been_acknowledged]
          in: query
          schema:
            type: boolean
          example: ""
          description: Filter by host status problem_has_been_acknowledged
        - name: filter[Hoststatus.scheduled_downtime_depth]
          in: query
          schema:
            type: boolean
          example: ""
          description: Filter by host status scheduled_downtime_depth
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getHostResponse'
      security:
        - ApiKeyAuth: []
  add:
    post:
      tags:
        - Hosts
      summary: "Add a new host"
      description: ""
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postHostsRequest'
      parameters:
        - name: angular
          in: query
          description: Use angular=true to get API results instead of a html template
          required: true
          schema:
            type: boolean
          example: true
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: 'http://ttriebensky-oitcweb.oitc.itn:81/globalschemas.yaml#/idResponse'
        500:
          description: "Webserver returns error code for OPTIONS request instead of right configured Access-Control-Allow-* headers"
      security:
        - ApiKeyAuth: []

  edit:
    post:
      tags:
        - Hosts
      summary: "Add a new host"
      description: ""
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postHostsRequest'
      parameters:
        - name: angular
          in: query
          description: Use angular=true to get API results instead of a html template
          required: true
          schema:
            type: boolean
          example: true
        - name: hostId
          in: path
          description: ID of the host to edit
          required: true
          schema:
            type: integer
          example: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: 'http://ttriebensky-oitcweb.oitc.itn:81/globalschemas.yaml#/idResponse'
        500:
          description: "Webserver returns error code for OPTIONS request instead of right configured Access-Control-Allow-* headers"
      security:
        - ApiKeyAuth: []

  delete:
    post:
      tags:
        - Hosts
      summary: "Delete a host"
      parameters:
        - name: angular
          in: query
          description: Use angular=true to get API results instead of a html template
          required: true
          schema:
            type: boolean
          example: true
        - name: hostId
          in: path
          description: ID of the host to delete
          required: true
          schema:
            type: integer
          example: 4
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: 'http://ttriebensky-oitcweb.oitc.itn:81/globalschemas.yaml#/successResponse'
      security:
        - ApiKeyAuth: []


components:
  schemas:
    getHostResponse:
      type: object
      properties:
        all_hosts:
          $ref: '#/components/schemas/getHostsResponseHostObject'
        scroll:
          $ref: 'http://ttriebensky-oitcweb.oitc.itn:81/globalschemas.yaml#/Scroll'
    getHostsResponseHostObject:
      type: "array"
      items:
        type: "object"
        anyOf:
          - $ref: "#/components/schemas/getHostsResponseHostArray"
    getHostsResponseHostArray:
      type: object
      properties:
        Host:
          type: object
          properties:
            id:
              type: integer
              format: "int64"
              example: 1
            uuid:
              type: string
              example: "c36b8048-93ce-4385-ac19-ab5c90574b77"
            hostname:
              type: string
              example: "default host"
            address:
              type: string
              example: "127.0.0.1"
            description:
              type: string
              example: ""
            active_checks_enabled:
              type: boolean
              example: ""
            satelliteId:
              type: integer
              format: "int64"
              example: 0
            containerId:
              type: integer
              format: "int64"
              example: 1
            containerIds:
              type: array
              items:
                type: integer
              example:
                - 1
                - 2
            tags:
              type: string
              example: ""
            allow_edit:
              type: boolean
              example: true
            disabled:
              type: boolean
              example: false
            is_satellite_host:
              type: boolean
              example: false
            has_graphs:
              type: boolean
              example: true
            allow_sharing:
              type: boolean
              example: true
            satelliteName:
              type: string
              example: Mastersystem
        Hoststatus:
          type: object
          properties:
            currentState:
              type: integer
              format: "int64"
              example: 0
            isFlapping:
              type: boolean
              example: ""
            problemHasBeenAcknowledged:
              type: boolean
              example: false
            scheduledDowntimeDepth:
              type: integer
              format: "int64"
              example: 0
            lastCheck:
              type: string
              example: "15:09:00 - 04.04.2019"
            nextCheck:
              type: string
              example: "17:09:00 - 04.04.2019"
            activeChecksEnabled:
              type: boolean
              example: true
            lastHardStateChange:
              type: string
              example: "15:39:16 - 25.03.2019"
            last_state_change:
              type: string
              example: "15:39:16 - 25.03.2019"
            output:
              type: string
              example: "OK - 127.0.0.1: rta 0.068ms, lost 0%"
            long_output:
              type: string
              example: ""
            acknowledgement_type:
              type: integer
              format: "int64"
              example: 0
            state_type:
              type: integer
              format: "int64"
              example: 1
            flap_detection_enabled:
              type: boolean
              example: ""
            notifications_enabled:
              type: boolean
              example: ""
            current_check_attempt:
              type: integer
              example: ""
            max_check_attempts:
              type: integer
              example: ""
            latency:
              type: integer
              example: ""
            isHardstate:
              type: boolean
              example: true
            isInMonitoring:
              type: boolean
              example: true
            humanState:
              type: string
              example: "up"
        ServicestatusSummary:
          type: object
          properties:
            state:
              type: object
              properties:
                ok:
                  type: integer
                  example: 3
                warning:
                  type: integer
                  example: 1
                critical:
                  type: integer
                  example: 0
                unknown:
                  type: integer
                  example: 0
            total:
              type: integer
              example: 4

    postHostsRequest:
      type: "object"
      required:
        - "Host"
      properties:
        Host:
          $ref: "#/components/schemas/postHostsRequestHost"
    postHostsRequestHost:
      type: "object"
      properties:
        name:
          type: string
          example: "example"
        description:
          type: string
          example: "default host"
        hosttemplate_id:
          type: integer
          format: "int64"
          example: 1
        address:
          type: string
          example: "ex.ample.com"
        command_id:
          type: integer
          format: "int64"
          example: 4
        eventhandler_command_id:
          type: integer
          format: "int64"
          example: 0
        check_interval:
          type: integer
          format: "int64"
          example: 7200
        retry_interval:
          type: integer
          format: "int64"
          example: 60
        max_check_attempts:
          type: integer
          format: "int64"
          example: 3
        first_notification_delay:
          type: integer
          format: "int64"
          example: 0
        notification_interval:
          type: integer
          format: "int64"
          example: 7200
        notify_on_down:
          type: integer
          format: "int64"
          example: 1
        notify_on_unreachable:
          type: integer
          format: "int64"
          example: 1
        notify_on_recovery:
          type: integer
          format: "int64"
          example: 1
        notify_on_flapping:
          type: integer
          format: "int64"
          example: 0
        notify_on_downtime:
          type: integer
          format: "int64"
          example: 0
        flap_detection_enabled:
          type: integer
          format: "int64"
          example: 0
        flap_detection_on_up:
          type: integer
          format: "int64"
          example: 0
        flap_detection_on_down:
          type: integer
          format: "int64"
          example: 0
        flap_detection_on_unreachable:
          type: integer
          format: "int64"
          example: 0
        low_flap_threshold:
          type: integer
          format: "int64"
          example: 0
        high_flap_threshold:
          type: integer
          format: "int64"
          example: 0
        process_performance_data:
          type: integer
          format: "int64"
          example: 0
        freshness_checks_enabled:
          type: integer
          format: "int64"
          example: 0
        freshness_threshold:
          type: integer
          format: "int64"
          example: 0
        passive_checks_enabled:
          type: integer
          format: "int64"
          example: 0
        event_handler_enabled:
          type: integer
          format: "int64"
          example: 0
        active_checks_enabled:
          type: integer
          format: "int64"
          example: 1
        retain_status_information:
          type: integer
          format: "int64"
          example: 0
        retain_nonstatus_information:
          type: integer
          format: "int64"
          example: 0
        notifications_enabled:
          type: integer
          format: "int64"
          example: 0
        notes:
          type: string
          example: "custom note"
        priority:
          type: integer
          format: "int64"
          minimum: 1
          maximum: 5
          example: 5
        check_period_id:
          type: integer
          format: "int64"
          example: 1
        notify_period_id:
          type: integer
          format: "int64"
          example: 1
        tags:
          type: string
          example: "ex,ample,api"
        container_id:
          type: integer
          format: "int64"
          example: 1
        host_url:
          type: string
          example: "https://test.example.org?host=$HOSTNAME$"
        satellite_id:
          type: integer
          format: "int64"
          example: 0
        contacts:
          type: object
          properties:
            _ids:
              type: array
              items:
                type: integer
                example: 1
        contactgroups:
          type: object
          properties:
            _ids:
              type: array
              items:
                type: integer
                example: 7
        hostgroups:
          type: object
          properties:
            _ids:
              type: array
              items:
                type: integer
                example: 1
        hosts_to_containers_sharing:
          type: object
          properties:
            _ids:
              type: array
              items:
                type: integer
                example: 2
        parenthosts:
          type: object
          properties:
            _ids:
              type: array
              items:
                type: integer
                example:
        customvariables:
          type: array
          items:
            type: object
            allOf:
              - $ref: "#/components/schemas/postHostsRequestHostCustomvariables"
        hostcommandargumentvalues:
          type: array
          items:
            type: object
            anyOf:
              - $ref: "#/components/schemas/postHostsRequestHostCommandargumentvalues1"
              - $ref: "#/components/schemas/postHostsRequestHostCommandargumentvalues2"

    postHostsRequestHostCustomvariables:
      type: "object"
      required:
        - objecttype_id
        - name
        - value
      properties:
        objecttype_id:
          type: integer
          example: 256
        name:
          type: string
          example: "TEST"
        value:
          type: string
          example: "examplevalue"
    postHostsRequestHostCommandargumentvalues1:
      type: "object"
      required:
        - commandargument_id
        - value
        - commandargument
      properties:
        commandargument_id:
          type: integer
          example: 3
        value:
          type: string
          example: "3000.0,80%"
        commandargument:
          type: object
          properties:
            name:
              type: string
              example: $ARG1$
            human_name:
              type: string
              example: Warning
            command_id:
              type: integer
              example: 4
    postHostsRequestHostCommandargumentvalues2:
      type: "object"
      required:
        - objecttype_id
        - value
        - commandargument
      properties:
        commandargument_id:
          type: integer
          example: 4
        value:
          type: string
          example: "5000.0,100%"
        commandargument:
          type: object
          properties:
            name:
              type: string
              example: $ARG2$
            human_name:
              type: string
              example: Critical
            command_id:
              type: integer
              example: 4
